import {
  FaComments,
  FaHome,
  FaProjectDiagram,
  FaUsers,
  FaCogs,
  FaUserShield,
  FaClock,
  FaAddressBook,
  FaSitemap,
  FaRobot,
  FaShoppingCart,
  FaChartLine,
} from 'react-icons/fa';

export const sidebarIcons: Record<string, JSX.Element> = {
  Estado: <FaHome />,
  Estadísticas: <FaChartLine />,
  Chat: <FaComments />,
  Chat2: <FaComments />,
  Flujos: <FaProjectDiagram />,
  'Flow Builder': <FaSitemap />,
  Bots: <FaRobot />,
  Pedidos: <FaShoppingCart />,
  Usuarios: <FaUsers />,
  Areas: <FaSitemap />,
  Contactos: <FaAddressBook />,
  Horarios: <FaClock />,
  Configuracion: <FaCogs />,
};
