ALTER TABLE `contacts`
  ADD COLUMN `obra_social` VARCHAR(255) NULL,
  ADD COLUMN `obra_social2` VARCHAR(255) NULL,
  ADD COLUMN `is_vip` BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN `is_problematic` BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN `is_chronic` BOOLEAN NOT NULL DEFAULT FALSE;
